services:
  frontend:
    image: ghcr.io/gardo32/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      # Base API URL for client-side requests (browser)
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      # The frontend code will detect other environments automatically
    networks:
      - app-network

  backend:
    image: ghcr.io/gardo32/backend:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      # Explicit origins to allow (beyond the auto-detected ones)
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
      # Add any other environment-specific variables here
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
