version: "3.8"

services:
  frontend:
    build:
      context: ./Net-Secure
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  backend:
    build:
      context: ./cipherx-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
